### ISSUE TITLE
Command not working

### ISSUE THREAD

**Issue by SirOMGitsYOU** [Scullyy/scully_mba#1]
Hey - I've setup the Ace and the group permissions etc but when doing the command and putting in any entityset it does not work! no errors or anything

**Comment by Gingerninja78** [comment]
it works with the older ineriors of the mba but i get the same issue with the new interiors

**Comment by SirOMGitsYOU** [comment]
> it works with the older ineriors of the mba but i get the same issue with the new interiors

I'm not able to get it to work with any :\

**Comment by Scullyy** [comment]
Not an issue, you set up your permissions incorrectly or are trying to use the new entity sets before Gabz announced that the update is finished.

**Comment by SirOMGitsYOU** [comment]
![image](https://user-images.githubusercontent.com/20475516/224788706-e9787be6-a7e8-4f9b-8dfe-680d0d82adf2.png)
If you could tell me where I'm going wrong because I'm using the old entitysets, and even trying /setmba none and its not working.
